title: LPLI1998
description: GitHub Pages site for my README
url: https://logi-web.github.io # root address of the site
baseurl: "/lpli1994"  # Match your repository name

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
