title: LPLI1998
description: GitHub Pages site for my README
remote_theme: riggraz/no-style-please
url: https://logi-web.github.io # root address of the site
baseurl: "/lpli1994"  # Match your repository name

favicon: favicon.svg

permalink: /:slug.html

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"

sass:
  style: compressed

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
