title: LPLI1998
description: GitHub Pages site for my README
markdown: kramdown
remote_theme: https://github.com/riggraz/no-style-please
baseurl: "/lpli1994"  # Match your repository name
favicon: favicon.svg
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
